export const SITE = {
  name: "Cason Landscaping",
  owner: "Kade Cason",
  phone: "(254) 434-3838",
  phoneHref: "tel:+12544343838",
  email: "Kadecason11@icloud.com",
  emailHref: "mailto:Kadecason11@icloud.com",
  city: "Stephenville, TX",
  facebook: "https://www.facebook.com/profile.php?id=61575816010968",
};

export const SERVICES = [
  {
    slug: "lawn-care",
    name: "Lawn Care",
    short: "Weekly mowing, edging, and clean-up that keeps the place tidy.",
    icon: "lawn-care" as const,
    long: "Routine mow, edge, line-trim, and blow-off so your yard always looks like somebody loves it. We sharpen blades, alternate mow patterns to reduce ruts, and bag or mulch depending on the season.",
    bullets: ["Mow at the right height for the season", "Edge driveways, walks, and beds", "String-trim around trees & fences", "Full blow-off of hard surfaces"],
  },
  {
    slug: "landscaping",
    name: "Landscaping",
    short: "Bed design, plant installs, and small hardscape touches.",
    icon: "landscaping" as const,
    long: "From a single bed refresh to a full front-yard rework we plan, plant, and place stone with an eye for what actually grows well in Erath County.",
    bullets: ["Bed shaping and edging", "Plant & shrub installation", "River-rock and stone borders", "Native, drought-tolerant choices"],
  },
  {
    slug: "mulching",
    name: "Mulching",
    short: "Fresh mulch that locks in moisture and makes beds pop.",
    icon: "mulching" as const,
    long: "Clean out the old, edge the bed, and lay a 2–3 inch blanket of fresh mulch. Choose hardwood, cedar, or dyed black/brown depending on the look you're after.",
    bullets: ["Weed pull and bed clean-out", "Crisp hand-cut edges", "2–3 in. even coverage", "Hardwood, cedar, or dyed options"],
  },
  {
    slug: "bush-trimming",
    name: "Bush Trimming",
    short: "Shape shrubs and hedges so the front of the house breathes.",
    icon: "bush-trimming" as const,
    long: "Shaping, thinning, and dead-wooding for shrubs and small ornamentals. Done at the right time of year so plants come back fuller.",
    bullets: ["Shape to natural or formal form", "Thin interior for airflow", "Remove dead and crossing branches", "Haul-off included"],
  },
  {
    slug: "leaf-removal",
    name: "Leaf Removal",
    short: "Fall and winter cleanups blown, bagged, and gone.",
    icon: "leaf-removal" as const,
    long: "We blow out beds, fence lines, and the lawn, then bag and haul. One-time or recurring through the leaf-drop season.",
    bullets: ["Beds, lawn, and fence lines", "Gutter-line clearing", "Bagged and hauled away", "One-time or recurring"],
  },
  {
    slug: "overseeding",
    name: "Overseeding",
    short: "Thicken thin lawns with the right seed for North Texas.",
    icon: "overseeding" as const,
    long: "Pair with aeration for best results. Seasonal seed choice (rye for winter color, bermuda or fescue blends otherwise) plus a starter feed.",
    bullets: ["Seasonal seed selection", "Even broadcast coverage", "Starter fertilizer included", "Watering schedule provided"],
  },
  {
    slug: "aeration",
    name: "Aeration",
    short: "Core-pull compacted soil so roots, water, and air get through.",
    icon: "aeration" as const,
    long: "Mechanical core aeration that pulls plugs not just spike rolling. Best done in growing season, often paired with overseeding and a top-dress.",
    bullets: ["True core-pull aeration", "Marks sprinklers before passing", "Pairs with overseeding", "Quick-recovery scheduling"],
  },
];